# Generated by Django 5.1.4 on 2024-12-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('num_bastidor', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre_modelo', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('potencia_fiscal', models.IntegerField()),
                ('cilindrada', models.IntegerField()),
                ('en_stock', models.BooleanField()),
                ('id_concesionario', models.IntegerField()),
                ('id_servicio', models.IntegerField()),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
